<?php
declare(strict_types=1);
require __DIR__ . '/../includes/site.php';
$posts = require __DIR__ . '/../src/Data/blog_en.php';
$slug = clean_text($_GET['slug'] ?? '', 100); $post = $posts[$slug] ?? null;
if (!$post) { http_response_code(404); site_header('Article not found', 'This article is not available.', '/en/blog.php', ['lang'=>'en','noindex'=>true,'breadcrumb'=>false,'alternates'=>['fr'=>site_url('blog.php'),'en'=>site_url('en/blog.php')]]); ?><section class="section"><div class="shell"><h1>Article not found.</h1><a class="button button--primary" href="<?= e(site_url('en/blog.php')) ?>">Back to guides</a></div></section><?php site_footer(); exit; }
$canonical=site_url('en/article.php?slug='.rawurlencode($slug)); $schema=['@type'=>'Article','@id'=>$canonical.'#article','headline'=>$post['title'],'description'=>$post['description'],'datePublished'=>$post['date'],'dateModified'=>$post['date'],'author'=>['@id'=>site_url('#person')],'publisher'=>['@id'=>site_url('#person')],'mainEntityOfPage'=>['@id'=>$canonical.'#webpage']];
site_header($post['title'],$post['description'],'/en/blog.php',['lang'=>'en','canonical'=>$canonical,'alternates'=>['fr'=>site_url('article.php?slug='.rawurlencode($slug)),'en'=>$canonical],'focus_keyword'=>$post['focus_keyword'] ?? '','schema_extra'=>[$schema]]);
?><article class="section article-page"><div class="shell article-shell"><header class="article-header"><p class="eyebrow"><span></span> <?= e($post['category']) ?> · <?= e($post['read_time']) ?></p><h1><?= e($post['title']) ?></h1><p class="article-intro"><?= e($post['intro']) ?></p></header><div class="article-content"><?php foreach ($post['sections'] as $section): ?><section><h2><?= e($section['title']) ?></h2><?php foreach ($section['paragraphs'] as $paragraph): ?><p><?= e($paragraph) ?></p><?php endforeach; ?></section><?php endforeach; ?></div><div class="article-cta"><h2>Planning a web project in Benin?</h2><p>If you are preparing a business website, web application or online store, let’s discuss your needs.</p><a class="button button--primary" href="<?= e(site_url('en/contact.php')) ?>">Discuss your project ↗</a></div></div></article><?php site_footer(); ?>
