<?php
declare(strict_types=1);
require __DIR__ . '/../includes/site.php';
$projects = portfolio_projects();
$projectsEn = array_map(static fn(array $p): array => translated_project($p, 'en'), $projects);
site_header('Home', 'Freelance web developer in Cotonou, Benin. Custom business websites, web applications and e-commerce solutions for local and international clients.', '/en/index.php', ['lang' => 'en', 'seo_key' => 'home', 'alternates' => ['fr' => site_url(), 'en' => site_url('en/')]]);
?>
<section class="hero"><div class="hero-noise" aria-hidden="true"></div><div class="shell hero-grid"><div class="hero-copy" data-reveal><p class="eyebrow"><span></span> Freelance web developer</p><h1>Your business deserves a web presence that is <em>clear, credible and useful.</em></h1><p class="hero-text">I build business websites, web applications and e-commerce experiences that build trust, simplify journeys and help businesses move forward.</p><div class="hero-actions"><a class="button button--primary" href="<?= e(site_url('en/contact.php')) ?>">Start a project <span aria-hidden="true">↗</span></a><a class="text-link" href="<?= e(site_url('en/projects.php')) ?>">View projects <span aria-hidden="true">↓</span></a></div><div class="hero-proof hero-proof--facts"><div class="proof-mark" aria-hidden="true">AKM</div><p><strong>From business websites to web applications.</strong><br>Solutions designed for entrepreneurs, SMEs and project owners.</p></div></div><div class="hero-art hero-art--portrait" data-reveal data-delay="120"><div class="portrait-glow" aria-hidden="true"></div><figure class="hero-portrait"><img src="<?= e(site_image_url(configured_hero_image())) ?>" alt="Portrait of Michael AKAKPOSSE, freelance web developer" width="900" height="1000" fetchpriority="high"><figcaption><span>Michael AKAKPOSSE</span><small>Freelance web developer</small></figcaption></figure><div class="code-card code-card--back"><span>const</span> idea = <i>impact</i>;</div><div class="code-card code-card--front"><span>design</span> + <i>logic</i> = <b>result</b></div><div class="hero-badge"><span>A digital presence<br>that feels like you</span></div></div></div><div class="shell hero-footer"><p>Building web experiences that serve your business.</p><a href="#projects" aria-label="Discover projects"><span>Scroll</span><i></i></a></div></section>
<section class="proof-strip" aria-label="Positioning"><div class="shell proof-strip-grid"><div><span>01</span><strong>Clarity</strong><p>Messages and journeys that are easy to understand.</p></div><div><span>02</span><strong>Credibility</strong><p>A coherent digital identity that reassures visitors.</p></div><div><span>03</span><strong>Utility</strong><p>Features designed around real business needs.</p></div><div><span>04</span><strong>Evolution</strong><p>A technical foundation designed to grow with you.</p></div></div></section>
<section class="section intro-section" id="projects"><div class="shell section-intro split-intro" data-reveal><div><p class="eyebrow"><span></span> Selected work</p><h2>Projects that start with a <em>real need.</em></h2></div><p>Every interface is designed to look good, but above all to help a business present itself, organise work or convert visitors.</p></div><div class="shell project-feature-grid"><?php foreach ($projectsEn as $index => $project): ?><article class="project-card <?= $index === 0 ? 'project-card--featured' : '' ?>" data-reveal data-delay="<?= $index * 80 ?>"><?php project_visual($project); ?><div class="project-card-content"><div class="project-card-meta"><span><?= e($project['label']) ?></span><span><?= e(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)) ?></span></div><h3><?= e($project['title']) ?></h3><p><?= e($project['summary']) ?></p><a class="circle-link" href="<?= e(site_url('en/project.php?slug=' . rawurlencode($project['slug']))) ?>" aria-label="Discover <?= e($project['title']) ?>">↗</a></div></article><?php endforeach; ?></div><div class="shell section-end"><a class="text-link text-link--large" href="<?= e(site_url('en/projects.php')) ?>">All projects <span aria-hidden="true">↗</span></a></div></section>
<section class="section services-preview"><div class="shell services-layout"><div data-reveal><p class="eyebrow"><span></span> My expertise</p><h2>A technical partner from <em>planning</em> to evolution.</h2><a class="button button--secondary" href="<?= e(site_url('en/services.php')) ?>">Explore services <span aria-hidden="true">↗</span></a></div><div class="service-list" data-reveal data-delay="100"><a href="<?= e(site_url('en/services.php#vitrine')) ?>"><span>01</span><strong>Business websites</strong><i>Present your business with precision and personality.</i><b>↗</b></a><a href="<?= e(site_url('en/services.php#applications')) ?>"><span>02</span><strong>Web applications</strong><i>Equip your teams with simple, useful workflows.</i><b>↗</b></a><a href="<?= e(site_url('en/services.php#commerce')) ?>"><span>03</span><strong>E-commerce</strong><i>Create a smooth path from discovery to purchase.</i><b>↗</b></a></div></div></section>
<section class="section local-seo-section"><div class="shell section-intro split-intro" data-reveal><div><p class="eyebrow"><span></span> Web development in Benin</p><h2>Freelance web development based in <em>Cotonou.</em></h2></div><p>I work with entrepreneurs, independent professionals and businesses in Benin and internationally to build websites and web applications adapted to their goals.</p></div></section>
<section class="section resources-preview"><div class="shell section-intro split-intro" data-reveal><div><p class="eyebrow"><span></span> Guides & resources</p><h2>Practical answers for <em>your next web project.</em></h2></div><p>Explore practical guides about website development, web applications and local SEO in Benin.</p></div><div class="shell project-feature-grid blog-grid"><?php foreach (array_slice(require __DIR__ . '/../src/Data/blog_en.php', 0, 3, true) as $slug => $post): ?><article class="project-card" data-reveal><div class="project-card-content"><div class="project-card-meta"><span><?= e($post['category']) ?></span><span><?= e($post['read_time']) ?></span></div><h3><?= e($post['title']) ?></h3><p><?= e($post['description']) ?></p><a class="text-link" href="<?= e(site_url('en/article.php?slug=' . rawurlencode($slug))) ?>">Read the guide ↗</a></div></article><?php endforeach; ?></div><div class="shell section-end"><a class="text-link text-link--large" href="<?= e(site_url('en/blog.php')) ?>">All guides <span aria-hidden="true">↗</span></a></div></section>

<section class="cta-panel-wrap"><div class="shell"><section class="cta-panel" data-reveal><p class="eyebrow eyebrow--light"><span></span> Your next project</p><h2>An idea deserves more than an ordinary website.</h2><p>Let’s discuss your goals and give them a digital presence that matters.</p><div><a class="button button--light" href="<?= e(site_url('en/contact.php')) ?>">Discuss your project <span aria-hidden="true">↗</span></a><a class="cta-email" href="mailto:<?= e(config('email')) ?>"><?= e(config('email')) ?></a></div></section></div></section>
<?php site_footer(); ?>
