<?php
declare(strict_types=1);
require __DIR__ . '/includes/site.php';
site_header('À propos', 'Découvrez Michael AKAKPOSSE, développeur web freelance à Cotonou, Bénin, spécialisé dans les sites web, applications métier et solutions digitales sur mesure.', '/a-propos.php', ['seo_key' => 'about', 'alternates' => ['fr' => site_url('a-propos.php'), 'en' => site_url('en/about.php')]]);
$heroImage = configured_hero_image();
?>
<section class="page-hero"><div class="shell page-hero-grid"><div data-reveal><p class="eyebrow"><span></span> À propos</p><h1>Développeur web freelance à Cotonou : donner une forme <em>juste</em> aux bonnes idées.</h1></div><p data-reveal data-delay="100">Je crée des expériences web qui trouvent le point de rencontre entre une identité forte, une logique métier solide et une utilisation évidente.</p></div></section>
<section class="section"><div class="shell about-grid"><div class="about-portrait about-portrait--photo" data-reveal><img src="<?= e(site_image_url($heroImage)) ?>" alt="Portrait de Michael AKAKPOSSE, développeur web freelance" width="1200" height="900" loading="lazy"><div class="portrait-note"><span>Disponible pour de nouveaux projets</span><i></i></div></div><div class="about-copy" data-reveal data-delay="100"><p class="eyebrow"><span></span> Ma démarche</p><h2>Le web est un outil. Il doit rendre une activité plus <em>lisible</em>, pas plus compliquée.</h2><p>J’accompagne les indépendants, PME et porteurs de projet qui veulent une présence numérique professionnelle ou un outil pensé pour leur manière de travailler.</p><p>Mon terrain de jeu : les sites vitrines qui créent de la confiance et les plateformes métier qui enlèvent des frictions au quotidien.</p><a class="text-link" href="<?= e(site_url('contact.php')) ?>">Travaillons ensemble <span>↗</span></a></div></div></section>
<section class="section section--muted"><div class="shell"><div class="section-intro split-intro" data-reveal><div><p class="eyebrow"><span></span> Stack technique</p><h2>Les bons outils, pour les <em>bonnes raisons.</em></h2></div><p>Je privilégie une base claire, performante et facile à faire évoluer : aucune complexité ajoutée juste pour suivre une tendance.</p></div><div class="skills-grid"><article data-reveal><span class="skill-number">01</span><h3>Front-end</h3><ul><li><b>HTML5 & accessibilité</b><span><i style="--level:92%"></i></span></li><li><b>CSS3 & responsive</b><span><i style="--level:90%"></i></span></li><li><b>JavaScript</b><span><i style="--level:82%"></i></span></li></ul></article><article data-reveal data-delay="90"><span class="skill-number">02</span><h3>Back-end</h3><ul><li><b>PHP natif</b><span><i style="--level:86%"></i></span></li><li><b>MySQL & modélisation</b><span><i style="--level:85%"></i></span></li><li><b>Sécurité applicative</b><span><i style="--level:80%"></i></span></li></ul></article><article data-reveal data-delay="180"><span class="skill-number">03</span><h3>Produit</h3><ul><li><b>UX & architecture</b><span><i style="--level:87%"></i></span></li><li><b>SEO technique</b><span><i style="--level:80%"></i></span></li><li><b>Déploiement</b><span><i style="--level:78%"></i></span></li></ul></article></div></div></section>
<section class="section"><div class="shell values-grid"><div data-reveal><p class="eyebrow"><span></span> Ce que vous pouvez attendre</p><h2>Un projet mené avec <em>clarté.</em></h2></div><div class="values-list"><article data-reveal><span>01</span><div><h3>Un langage simple</h3><p>Les choix techniques sont expliqués sans jargon. Vous savez ce qui est fait, pourquoi et pour qui.</p></div></article><article data-reveal><span>02</span><div><h3>Une exigence utile</h3><p>Chaque détail visuel ou technique doit servir la compréhension, la confiance ou la performance.</p></div></article><article data-reveal><span>03</span><div><h3>Un site qui vous appartient</h3><p>Une base propre et documentée pour vous permettre de conserver la maîtrise de votre projet.</p></div></article></div></div></section>
<?php site_footer(); ?>
