<?php
declare(strict_types=1);
require __DIR__ . '/includes/site.php';
site_header('Services', 'Création de sites web, applications métier et e-commerce sur mesure à Cotonou et au Bénin, avec une approche claire, responsive, performante et SEO-friendly.', '/services.php', ['seo_key' => 'services', 'alternates' => ['fr' => site_url('services.php'), 'en' => site_url('en/services.php')]]);
?>
<section class="services-hero">
  <div class="services-hero-shape shape-one" aria-hidden="true"></div><div class="services-hero-shape shape-two" aria-hidden="true"></div>
  <div class="shell services-hero-grid"><div class="services-hero-copy" data-reveal><p class="eyebrow"><span></span> Services web sur mesure</p><h1>Création de sites web et applications sur mesure à <em>Cotonou.</em></h1><p>Chaque projet commence par une question simple : qu’est-ce que votre site doit réellement permettre à votre activité, à vos clients ou à votre équipe ?</p><div class="hero-actions"><a class="button button--primary" href="<?= e(site_url('contact.php')) ?>">Parler de votre projet <span>↗</span></a><a class="text-link" href="#offres">Découvrir les offres <span>↓</span></a></div></div><aside class="services-hero-card" data-reveal data-delay="120"><span class="services-card-tag">Approche complète</span><div class="services-card-mark">01—03</div><h2>Une présence numérique qui reste claire, même quand votre activité devient ambitieuse.</h2><ul><li><i>✓</i> Stratégie et structure</li><li><i>✓</i> Direction artistique</li><li><i>✓</i> Développement et mise en ligne</li></ul></aside></div>
</section>

<nav class="service-anchor-bar" aria-label="Explorer les services"><div class="shell"><a href="#vitrine"><span>01</span> Site vitrine <b>↘</b></a><a href="#applications"><span>02</span> Application métier <b>↘</b></a><a href="#commerce"><span>03</span> E-commerce <b>↘</b></a></div></nav>

<section class="services-showcase" id="offres"><div class="shell">
  <article class="service-showcase-card" id="vitrine" data-reveal><div class="service-showcase-copy"><p class="eyebrow"><span></span> 01 · Site vitrine</p><h2>Présentez votre valeur avec une présence qui inspire <em>confiance.</em></h2><p>Un site vitrine ne doit pas seulement donner des informations. Il doit mettre vos futurs clients à l’aise, rendre votre différence visible et faciliter la prise de contact.</p><ul class="service-benefits"><li><b>Positionnement lisible</b><span>Une architecture et des contenus qui vont droit à l’essentiel.</span></li><li><b>Design singulier</b><span>Une identité adaptée à votre activité, pas un modèle réutilisé.</span></li><li><b>Conversion naturelle</b><span>Des appels à l’action et un contact accessibles à chaque étape.</span></li></ul><a class="text-link" href="<?= e(site_url('contact.php')) ?>">Imaginer mon site vitrine <span>↗</span></a></div><figure class="service-showcase-visual"><div class="service-visual-art" aria-hidden="true"><span class="service-art-window"></span><span class="service-art-line service-art-line--one"></span><span class="service-art-line service-art-line--two"></span><span class="service-art-pill"></span></div><figcaption><span>Clarté</span><strong>Une première impression qui compte.</strong></figcaption></figure></article>
  <article class="service-showcase-card service-showcase-card--reverse" id="applications" data-reveal><div class="service-showcase-copy"><p class="eyebrow"><span></span> 02 · Application métier</p><h2>Transformez les tâches répétitives en parcours <em>fluides.</em></h2><p>Quand un tableur ne suffit plus, une application bien pensée permet à chaque personne de retrouver la bonne information et de réaliser les bonnes actions, simplement.</p><ul class="service-benefits"><li><b>Analyse du besoin</b><span>Des flux réels avant le premier écran ou la première ligne de code.</span></li><li><b>Rôles et données</b><span>Les accès, statuts et informations qui comptent pour chaque utilisateur.</span></li><li><b>Pilotage utile</b><span>Des tableaux de bord qui aident à décider, pas seulement à regarder.</span></li></ul><a class="text-link" href="<?= e(site_url('contact.php')) ?>">Parler de mon application <span>↗</span></a></div><figure class="service-showcase-visual"><div class="service-visual-art" aria-hidden="true"><span class="service-art-window"></span><span class="service-art-line service-art-line--one"></span><span class="service-art-line service-art-line--two"></span><span class="service-art-pill"></span></div><figcaption><span>Efficacité</span><strong>Un outil fait pour le quotidien.</strong></figcaption></figure></article>
  <article class="service-showcase-card" id="commerce" data-reveal><div class="service-showcase-copy"><p class="eyebrow"><span></span> 03 · E-commerce</p><h2>Rendez le chemin vers l’achat plus simple, plus rassurant et plus <em>désirable.</em></h2><p>Une boutique performante équilibre l’image de marque, la clarté des produits et une expérience d’achat qui ne crée aucune hésitation sur mobile comme sur ordinateur.</p><ul class="service-benefits"><li><b>Catalogue lisible</b><span>Des produits faciles à parcourir et à comparer.</span></li><li><b>Parcours rassurant</b><span>Les informations utiles arrivent exactement au bon moment.</span></li><li><b>Base évolutive</b><span>Une solution pensée pour accompagner votre offre dans le temps.</span></li></ul><a class="text-link" href="<?= e(site_url('contact.php')) ?>">Parler de ma boutique <span>↗</span></a></div><figure class="service-showcase-visual"><div class="service-visual-art" aria-hidden="true"><span class="service-art-window"></span><span class="service-art-line service-art-line--one"></span><span class="service-art-line service-art-line--two"></span><span class="service-art-pill"></span></div><figcaption><span>Conversion</span><strong>Le bon rythme, du produit à la commande.</strong></figcaption></figure></article>
</div></section>

<section class="section local-seo-section"><div class="shell section-intro split-intro" data-reveal><div><p class="eyebrow"><span></span> Développement web au Bénin</p><h2>Création de sites web à <em>Cotonou et au Bénin.</em></h2></div><p>Je conçois des sites vitrines, applications web et solutions e-commerce pour les entrepreneurs, PME et entreprises qui souhaitent développer leur présence en ligne au Bénin et à l’international.</p></div></section>

<section class="services-method"><div class="shell"><div class="services-method-intro" data-reveal><p class="eyebrow"><span></span> Une méthode concrète</p><h2>On avance par bonnes décisions, pas par effet de <em>style.</em></h2></div><ol class="services-method-steps"><li data-reveal><span>01</span><div><h3>Cadrer</h3><p>Objectifs, utilisateurs, contenus et contraintes : nous créons un terrain de jeu clair.</p></div></li><li data-reveal data-delay="80"><span>02</span><div><h3>Concevoir</h3><p>Les parcours, l’univers visuel et les interfaces trouvent leur forme juste.</p></div></li><li data-reveal data-delay="160"><span>03</span><div><h3>Construire</h3><p>Le projet prend vie avec une base performante, accessible et maintenable.</p></div></li><li data-reveal data-delay="240"><span>04</span><div><h3>Faire évoluer</h3><p>Après la mise en ligne, le site peut continuer à grandir avec vos besoins.</p></div></li></ol></div></section>

<section class="services-proof"><div class="shell services-proof-grid"><div data-reveal><p class="eyebrow eyebrow--light"><span></span> Un accompagnement à votre rythme</p><h2>Une relation simple, des choix expliqués et un projet qui vous <em>appartient.</em></h2></div><div class="services-proof-list" data-reveal data-delay="100"><p><span>01</span> Pas de jargon inutile : chaque choix reste compréhensible.</p><p><span>02</span> Un interlocuteur unique du début jusqu’à la mise en ligne.</p><p><span>03</span> Une base propre pour faire évoluer votre site sans repartir de zéro.</p><a class="button button--light" href="<?= e(site_url('contact.php')) ?>">Recevoir des recommandations <span>↗</span></a></div></div></section>

<section class="section services-faq"><div class="shell faq-grid"><div data-reveal><p class="eyebrow"><span></span> Questions fréquentes</p><h2>Ce qu’il faut savoir avant de <em>commencer.</em></h2></div><div class="faq-list" data-reveal data-delay="100"><details><summary>Comment démarre un projet ? <span>+</span></summary><p>Par un échange sur votre besoin, vos objectifs, votre public et les contraintes du projet. Cela permet de cadrer une solution réellement adaptée.</p></details><details><summary>Est-ce que je peux faire évoluer mon site ensuite ? <span>+</span></summary><p>Oui. Les projets sont pensés avec une base maintenable afin de pouvoir ajouter ou ajuster des fonctionnalités avec méthode.</p></details><details><summary>Quel budget prévoir ? <span>+</span></summary><p>Le budget dépend du périmètre. Le formulaire de contact permet de situer votre besoin sans engagement, puis un devis adapté peut être préparé.</p></details></div></div></section>
<?php site_footer(); ?>
