<?php
declare(strict_types=1);
$lang = (($GLOBALS['site_lang'] ?? 'fr') === 'en') ? 'en' : 'fr';
$t = static fn(string $fr, string $en): string => $lang === 'en' ? $en : $fr;
?>
<form class="contact-form" action="<?= e(site_url('api/contact.php')) ?>" method="post" novalidate data-contact-form>
  <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
  <div class="form-honeypot" aria-hidden="true"><label for="website"><?= e($t('Ne pas renseigner ce champ', 'Leave this field empty')) ?></label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
  <div class="form-grid">
    <div class="field"><label for="name"><?= e($t('Nom', 'Name')) ?> <span aria-hidden="true">*</span></label><input id="name" name="name" type="text" autocomplete="name" minlength="2" maxlength="100" required><p class="field-error" id="name-error"></p></div>
    <div class="field"><label for="email"><?= e($t('E-mail', 'Email')) ?> <span aria-hidden="true">*</span></label><input id="email" name="email" type="email" autocomplete="email" maxlength="150" required><p class="field-error" id="email-error"></p></div>
    <div class="field"><label for="phone"><?= e($t('Téléphone', 'Phone')) ?> <span class="optional"><?= e($t('optionnel', 'optional')) ?></span></label><input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" maxlength="20"><p class="field-error" id="phone-error"></p></div>
    <div class="field"><label for="project_type"><?= e($t('Type de projet', 'Project type')) ?> <span aria-hidden="true">*</span></label><select id="project_type" name="project_type" required><option value=""><?= e($t('Choisir une option', 'Choose an option')) ?></option><option value="<?= e($t('Site vitrine', 'Business website')) ?>"><?= e($t('Site vitrine', 'Business website')) ?></option><option value="<?= e($t('Application web', 'Web application')) ?>"><?= e($t('Application web', 'Web application')) ?></option><option value="E-commerce">E-commerce</option><option value="<?= e($t('Autre', 'Other')) ?>"><?= e($t('Autre', 'Other')) ?></option></select><p class="field-error" id="project_type-error"></p></div>
    <div class="field"><label for="budget"><?= e($t('Budget indicatif', 'Indicative budget')) ?> <span aria-hidden="true">*</span></label><select id="budget" name="budget" required><option value=""><?= e($t('Choisir une tranche', 'Choose a range')) ?></option><option value="<?= e($t('Moins de 500€', 'Less than €500')) ?>"><?= e($t('Moins de 500 €', 'Less than €500')) ?></option><option value="<?= e($t('500€ - 1000€', '€500 - €1,000')) ?>"><?= e($t('500 € – 1 000 €', '€500 – €1,000')) ?></option><option value="<?= e($t('1000€ - 3000€', '€1,000 - €3,000')) ?>"><?= e($t('1 000 € – 3 000 €', '€1,000 – €3,000')) ?></option><option value="<?= e($t('3000€ - 5000€', '€3,000 - €5,000')) ?>"><?= e($t('3 000 € – 5 000 €', '€3,000 – €5,000')) ?></option><option value="<?= e($t('Plus de 5000€', 'More than €5,000')) ?>"><?= e($t('Plus de 5 000 €', 'More than €5,000')) ?></option><option value="<?= e($t('Non précisé', 'Not specified')) ?>"><?= e($t('Je préfère en discuter', 'I prefer to discuss')) ?></option></select><p class="field-error" id="budget-error"></p></div>
    <div class="field"><label for="deadline"><?= e($t('Délai souhaité', 'Desired timeline')) ?> <span aria-hidden="true">*</span></label><select id="deadline" name="deadline" required><option value=""><?= e($t('Choisir un délai', 'Choose a timeline')) ?></option><option value="<?= e($t('Dès que possible', 'As soon as possible')) ?>"><?= e($t('Dès que possible', 'As soon as possible')) ?></option><option value="<?= e($t('Dans le mois', 'Within a month')) ?>"><?= e($t('Dans le mois', 'Within a month')) ?></option><option value="<?= e($t('Dans 1 à 3 mois', 'Within 1–3 months')) ?>"><?= e($t('Dans 1 à 3 mois', 'Within 1–3 months')) ?></option><option value="<?= e($t('Plus de 3 mois', 'More than 3 months')) ?>"><?= e($t('Plus de 3 mois', 'More than 3 months')) ?></option><option value="<?= e($t('À définir ensemble', 'To be defined together')) ?>"><?= e($t('À définir ensemble', 'To be defined together')) ?></option></select><p class="field-error" id="deadline-error"></p></div>
    <div class="field field--wide"><label for="message"><?= e($t('Parlez-moi de votre besoin', 'Tell me about your needs')) ?> <span aria-hidden="true">*</span></label><textarea id="message" name="message" rows="6" minlength="30" maxlength="2000" required placeholder="<?= e($t('Contexte, objectif, fonctionnalités importantes…', 'Context, goals, key features…')) ?>"></textarea><div class="field-meta"><p class="field-error" id="message-error"></p><span data-character-count>0 / 2 000</span></div></div>
  </div>
  <label class="checkbox-field" for="consent"><input id="consent" name="consent" type="checkbox" value="1" required><span><?= e($t('J’accepte que mes informations soient utilisées pour répondre à ma demande.', 'I agree that my information may be used to answer my request.')) ?> <span aria-hidden="true">*</span></span></label>
  <p class="field-error" id="consent-error"></p><button class="button button--primary button--full" type="submit" data-submit-button><?= e($t('Envoyer ma demande', 'Send my request')) ?> <span aria-hidden="true">↗</span></button><p class="form-status" role="status" aria-live="polite" data-form-status></p><p class="form-note"><?= e($t('Réponse sous 24–48 h ouvrées. Vos données ne sont jamais revendues.', 'Reply within 24–48 business hours. Your data is never sold.')) ?></p>
</form>
